apiVersion: v1
kind: Service
metadata:
  name: nodejs-task-service
  namespace: nodejs-task
  labels:
    app: nodejs-task
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "nodejs-task-lb"
spec:
  type: LoadBalancer
  selector:
    app: nodejs-task
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: None